---
title: "Data processing and EDA"
author: "Melody Jiang"
date: "1/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(42)
library(ggplot2)
```

```{r}
dat = readRDS("Longnecker.rds")
dat$center = factor(dat$center)
dat$smoking_status = factor(dat$smoking_status)

dat = dat[-1861,]
library(mice)
dat = dat[,!names(dat) %in% c('albumin')]
imp = mice(dat)
dat = complete(imp)

dat$ind_37 = dat$gestational_age < 37

dat[,c(1:12,13,15,16,17,18,20)] = scale(dat[,c(1:12,13,15,16,17,18,20)]) # standardize
```

```{r}
dat_orig = readRDS("Longnecker.rds")
summary(dat_orig)
```

```{r}
corrplot::corrplot(cor(dat %>% dplyr::select(dde, pcb_028:pcb_203, triglycerides, cholesterol, ind_37)))
```

```{r}
ggplot(dat, aes(x = ind_37, y = dde, group = ind_37)) +
  geom_boxplot(aes(fill=ind_37)) + 
  labs(fill = "early delivery", x = "early delivery")
```

```{r}
pca = princomp(dat[,2:12])
pcb = as.matrix(dat[,2:12])
pcb_pc = pcb %*% pca$loadings
print(pca$loadings)
summary(pca)
```

```{r}
ggplot(dat, aes(x = ind_37, y = as.matrix(dat %>% dplyr::select(pcb_028:pcb_203)) %*% as.vector(pca$loadings[,1]), group = ind_37)) +
  geom_boxplot(aes(fill=ind_37)) + 
  labs(fill = "early delivery", x = "early delivery", y = "weighted sum of pcb by first column of loadings matrix")
```

```{r}
# race and early delivery
dat_temp <- as.data.frame(table(dat$race, dat$ind_37))
ggplot(dat_temp, aes(x = Var1, y = Freq, fill = Var2)) + 
    geom_bar(position = "fill",stat = "identity") +
    # or:
    # geom_bar(position = position_fill(), stat = "identity") 
    scale_y_continuous(labels = scales::percent_format())
```

```{r}
# dde by race
ggplot(dat, aes(x = race, y = dde, group = race)) +
  geom_boxplot(aes(fill=race)) + 
  labs(fill = "race", x = "race")
```

```{r}
ggplot(dat, aes(x = race, y = as.matrix(dat %>% dplyr::select(pcb_028:pcb_203)) %*% as.vector(pca$loadings[,1]), group = race)) +
  geom_boxplot(aes(fill=race)) + 
  labs(fill = "race", x = "race", y = "weighted sum of pcb by first column of loadings matrix")
```

```{r}
scaleFUN <- function(x) sprintf("%.2f", x)
```

```{r}
dat_temp <- as.data.frame(table(dat$maternal_age, dat$ind_37))
ggplot(dat_temp, aes(x = Var1, y = Freq, fill = Var2)) + 
    geom_bar(position = "fill",stat = "identity") +
    # or:
    # geom_bar(position = position_fill(), stat = "identity") 
    scale_y_continuous(labels = scales::percent_format()) +
  labs(fill = "Preterm delivery", x = "Scaled age of mother", y = "Proportion of early delivery") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


